name: "Automatic build"
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Use Node.js 16 # 添加这一步骤
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Deploy
        run: bash tools/deploy.sh
